
 <div class="row">
    <div class="col-sm">     
    <img style="width:250px; height:250px" src="<?php echo $this->url->getBaseUri().'public/img/profilex.png'; ?>">
    </div>
<div class="col-sm">

  <div class="form-group" >
  <h1>YOORADET KHAMON</h1>
  </div>
  <div class="form-group">
 <h2> 590610650</h2>
  </div>
  <div class="form-group">

  </div> 
    </div>
    <div class="col-sm">     
    </div>
  </div>